# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyImageSearchApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyImageSearchApp
    pod 'Alamofire'
    pod 'SnapKit'
    pod 'Kingfisher'
    pod 'RxSwift'
    pod 'RxCocoa'
end
